<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Language::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $data = array(
            array("code" => "aa", "name" => "Afar"),
            array("code" => "af", "name" => "Afrikaans"),
            array("code" => "ak", "name" => "Akan"),
            array("code" => "tw", "name" => "Akan, Twi"),
            array("code" => "sq", "name" => "Albanian"),
            array("code" => "am", "name" => "Amharic"),
            array("code" => "ar", "name" => "Arabic"),
            array("code" => "ar-BH", "name" => "Arabic, Bahrain"),
            array("code" => "ar-EG", "name" => "Arabic, Egypt"),
            array("code" => "ar-SA", "name" => "Arabic, Saudi Arabia"),
            array("code" => "ar-YE", "name" => "Arabic, Yemen"),
            array("code" => "an", "name" => "Aragonese"),
            array("code" => "hy-AM", "name" => "Armenian"),
            array("code" => "frp", "name" => "Arpitan"),
            array("code" => "as", "name" => "Assamese"),
            array("code" => "ast", "name" => "Asturian"),
            array("code" => "tay", "name" => "Atayal"),
            array("code" => "av", "name" => "Avaric"),
            array("code" => "ae", "name" => "Avestan"),
            array("code" => "ay", "name" => "Aymara"),
            array("code" => "az", "name" => "Azerbaijani"),
            array("code" => "ban", "name" => "Balinese"),
            array("code" => "bal", "name" => "Balochi"),
            array("code" => "bm", "name" => "Bambara"),
            array("code" => "ba", "name" => "Bashkir"),
            array("code" => "eu", "name" => "Basque"),
            array("code" => "be", "name" => "Belarusian"),
            array("code" => "bn", "name" => "Bengali"),
            array("code" => "bn-IN", "name" => "Bengali, India"),
            array("code" => "ber", "name" => "Berber"),
            array("code" => "bh", "name" => "Bihari"),
            array("code" => "bfo", "name" => "Birifor"),
            array("code" => "bi", "name" => "Bislama"),
            array("code" => "bs", "name" => "Bosnian"),
            array("code" => "br-FR", "name" => "Breton"),
            array("code" => "bg", "name" => "Bulgarian"),
            array("code" => "my", "name" => "Burmese"),
            array("code" => "ca", "name" => "Catalan"),
            array("code" => "ceb", "name" => "Cebuano"),
            array("code" => "ch", "name" => "Chamorro"),
            array("code" => "ce", "name" => "Chechen"),
            array("code" => "chr", "name" => "Cherokee"),
            array("code" => "ny", "name" => "Chewa"),
            array("code" => "zh-CN", "name" => "Chinese Simplified"),
            array("code" => "zh-TW", "name" => "Chinese Traditional"),
            array("code" => "zh-HK", "name" => "Chinese Traditional, Hong Kong"),
            array("code" => "zh-MO", "name" => "Chinese Traditional, Macau"),
            array("code" => "zh-SG", "name" => "Chinese Traditional, Singapore"),
            array("code" => "cv", "name" => "Chuvash"),
            array("code" => "kw", "name" => "Cornish"),
            array("code" => "co", "name" => "Corsican"),
            array("code" => "cr", "name" => "Cree"),
            array("code" => "hr", "name" => "Croatian"),
            array("code" => "cs", "name" => "Czech"),
            array("code" => "da", "name" => "Danish"),
            array("code" => "fa-AF", "name" => "Dari"),
            array("code" => "dv", "name" => "Dhivehi"),
            array("code" => "nl", "name" => "Dutch"),
            array("code" => "nl-BE", "name" => "Dutch, Belgium"),
            array("code" => "nl-SR", "name" => "Dutch, Suriname"),
            array("code" => "dz", "name" => "Dzongkha"),
            array("code" => "en", "name" => "English"),
            array("code" => "en-UD", "name" => "English (upside down)"),
            array("code" => "en-AR", "name" => "English, Arabia"),
            array("code" => "en-AU", "name" => "English, Australia"),
            array("code" => "en-BZ", "name" => "English, Belize"),
            array("code" => "en-CA", "name" => "English, Canada"),
            array("code" => "en-CB", "name" => "English, Caribbean"),
            array("code" => "en-CN", "name" => "English, China"),
            array("code" => "en-DK", "name" => "English, Denmark"),
            array("code" => "en-HK", "name" => "English, Hong Kong"),
            array("code" => "en-IN", "name" => "English, India"),
            array("code" => "en-ID", "name" => "English, Indonesia"),
            array("code" => "en-IE", "name" => "English, Ireland"),
            array("code" => "en-JM", "name" => "English, Jamaica"),
            array("code" => "en-JA", "name" => "English, Japan"),
            array("code" => "en-MY", "name" => "English, Malaysia"),
            array("code" => "en-NZ", "name" => "English, New Zealand"),
            array("code" => "en-NO", "name" => "English, Norway"),
            array("code" => "en-PH", "name" => "English, Philippines"),
            array("code" => "en-PR", "name" => "English, Puerto Rico"),
            array("code" => "en-SG", "name" => "English, Singapore"),
            array("code" => "en-ZA", "name" => "English, South Africa"),
            array("code" => "en-SE", "name" => "English, Sweden"),
            array("code" => "en-GB", "name" => "English, United Kingdom"),
            array("code" => "en-US", "name" => "English, United States"),
            array("code" => "en-ZW", "name" => "English, Zimbabwe"),
            array("code" => "eo", "name" => "Esperanto"),
            array("code" => "et", "name" => "Estonian"),
            array("code" => "ee", "name" => "Ewe"),
            array("code" => "fo", "name" => "Faroese"),
            array("code" => "fj", "name" => "Fijian"),
            array("code" => "fil", "name" => "Filipino"),
            array("code" => "fi", "name" => "Finnish"),
            array("code" => "vls-BE", "name" => "Flemish"),
            array("code" => "fra-DE", "name" => "Franconian"),
            array("code" => "fr", "name" => "French"),
            array("code" => "fr-BE", "name" => "French, Belgium"),
            array("code" => "fr-CA", "name" => "French, Canada"),
            array("code" => "fr-LU", "name" => "French, Luxembourg"),
            array("code" => "fr-QC", "name" => "French, Quebec"),
            array("code" => "fr-CH", "name" => "French, Switzerland"),
            array("code" => "fy-NL", "name" => "Frisian"),
            array("code" => "fur-IT", "name" => "Friulian"),
            array("code" => "ff", "name" => "Fula"),
            array("code" => "gaa", "name" => "Ga"),
            array("code" => "gl", "name" => "Galician"),
            array("code" => "ka", "name" => "Georgian"),
            array("code" => "de", "name" => "German"),
            array("code" => "de-AT", "name" => "German, Austria"),
            array("code" => "de-BE", "name" => "German, Belgium"),
            array("code" => "de-LI", "name" => "German, Liechtenstein"),
            array("code" => "de-LU", "name" => "German, Luxembourg"),
            array("code" => "de-CH", "name" => "German, Switzerland"),
            array("code" => "got", "name" => "Gothic"),
            array("code" => "el", "name" => "Greek"),
            array("code" => "el-CY", "name" => "Greek, Cyprus"),
            array("code" => "kl", "name" => "Greenlandic"),
            array("code" => "gn", "name" => "Guarani"),
            array("code" => "gu-IN", "name" => "Gujarati"),
            array("code" => "ht", "name" => "Haitian Creole"),
            array("code" => "ha", "name" => "Hausa"),
            array("code" => "haw", "name" => "Hawaiian"),
            array("code" => "he", "name" => "Hebrew"),
            array("code" => "hz", "name" => "Herero"),
            array("code" => "hil", "name" => "Hiligaynon"),
            array("code" => "hi", "name" => "Hindi"),
            array("code" => "ho", "name" => "Hiri Motu"),
            array("code" => "hmn", "name" => "Hmong"),
            array("code" => "hu", "name" => "Hungarian"),
            array("code" => "is", "name" => "Icelandic"),
            array("code" => "ido", "name" => "Ido"),
            array("code" => "ig", "name" => "Igbo"),
            array("code" => "ilo", "name" => "Ilokano"),
            array("code" => "id", "name" => "Indonesian"),
            array("code" => "iu", "name" => "Inuktitut"),
            array("code" => "ga-IE", "name" => "Irish"),
            array("code" => "it", "name" => "Italian"),
            array("code" => "it-CH", "name" => "Italian, Switzerland"),
            array("code" => "ja", "name" => "Japanese"),
            array("code" => "jv", "name" => "Javanese"),
            array("code" => "quc", "name" => "K'iche'"),
            array("code" => "kab", "name" => "Kabyle"),
            array("code" => "kn", "name" => "Kannada"),
            array("code" => "pam", "name" => "Kapampangan"),
            array("code" => "ks", "name" => "Kashmiri"),
            array("code" => "ks-PK", "name" => "Kashmiri, Pakistan"),
            array("code" => "csb", "name" => "Kashubian"),
            array("code" => "kk", "name" => "Kazakh"),
            array("code" => "km", "name" => "Khmer"),
            array("code" => "rw", "name" => "Kinyarwanda"),
            array("code" => "tlh-AA", "name" => "Klingon"),
            array("code" => "kv", "name" => "Komi"),
            array("code" => "kg", "name" => "Kongo"),
            array("code" => "kok", "name" => "Konkani"),
            array("code" => "ko", "name" => "Korean"),
            array("code" => "ku", "name" => "Kurdish"),
            array("code" => "kmr", "name" => "Kurmanji (Kurdish)"),
            array("code" => "kj", "name" => "Kwanyama"),
            array("code" => "ky", "name" => "Kyrgyz"),
            array("code" => "lol", "name" => "LOLCAT"),
            array("code" => "lo", "name" => "Lao"),
            array("code" => "la-LA", "name" => "Latin"),
            array("code" => "lv", "name" => "Latvian"),
            array("code" => "lij", "name" => "Ligurian"),
            array("code" => "li", "name" => "Limburgish"),
            array("code" => "ln", "name" => "Lingala"),
            array("code" => "lt", "name" => "Lithuanian"),
            array("code" => "jbo", "name" => "Lojban"),
            array("code" => "nds", "name" => "Low German"),
            array("code" => "dsb-DE", "name" => "Lower Sorbian"),
            array("code" => "lg", "name" => "Luganda"),
            array("code" => "luy", "name" => "Luhya"),
            array("code" => "lb", "name" => "Luxembourgish"),
            array("code" => "mk", "name" => "Macedonian"),
            array("code" => "mai", "name" => "Maithili"),
            array("code" => "mg", "name" => "Malagasy"),
            array("code" => "ms", "name" => "Malay"),
            array("code" => "ms-BN", "name" => "Malay, Brunei"),
            array("code" => "ml-IN", "name" => "Malayalam"),
            array("code" => "mt", "name" => "Maltese"),
            array("code" => "gv", "name" => "Manx"),
            array("code" => "mi", "name" => "Maori"),
            array("code" => "arn", "name" => "Mapudungun"),
            array("code" => "mr", "name" => "Marathi"),
            array("code" => "mh", "name" => "Marshallese"),
            array("code" => "moh", "name" => "Mohawk"),
            array("code" => "mn", "name" => "Mongolian"),
            array("code" => "sr-Cyrl-ME", "name" => "Montenegrin (Cyrillic)"),
            array("code" => "me", "name" => "Montenegrin (Latin)"),
            array("code" => "mos", "name" => "Mossi"),
            array("code" => "na", "name" => "Nauru"),
            array("code" => "ng", "name" => "Ndonga"),
            array("code" => "ne-NP", "name" => "Nepali"),
            array("code" => "ne-IN", "name" => "Nepali, India"),
            array("code" => "pcm", "name" => "Nigerian Pidgin"),
            array("code" => "se", "name" => "Northern Sami"),
            array("code" => "nso", "name" => "Northern Sotho"),
            array("code" => "no", "name" => "Norwegian"),
            array("code" => "nb", "name" => "Norwegian Bokmal"),
            array("code" => "nn-NO", "name" => "Norwegian Nynorsk"),
            array("code" => "oc", "name" => "Occitan"),
            array("code" => "or", "name" => "Odia"),
            array("code" => "oj", "name" => "Ojibwe"),
            array("code" => "om", "name" => "Oromo"),
            array("code" => "os", "name" => "Ossetian"),
            array("code" => "pi", "name" => "Pali"),
            array("code" => "pap", "name" => "Papiamento"),
            array("code" => "ps", "name" => "Pashto"),
            array("code" => "fa", "name" => "Persian"),
            array("code" => "en-PT", "name" => "Pirate English"),
            array("code" => "pl", "name" => "Polish"),
            array("code" => "pt-PT", "name" => "Portuguese"),
            array("code" => "pt-BR", "name" => "Portuguese, Brazilian"),
            array("code" => "pa-IN", "name" => "Punjabi"),
            array("code" => "pa-PK", "name" => "Punjabi, Pakistan"),
            array("code" => "qu", "name" => "Quechua"),
            array("code" => "qya-AA", "name" => "Quenya"),
            array("code" => "ro", "name" => "Romanian"),
            array("code" => "rm-CH", "name" => "Romansh"),
            array("code" => "rn", "name" => "Rundi"),
            array("code" => "ru", "name" => "Russian"),
            array("code" => "ru-BY", "name" => "Russian, Belarus"),
            array("code" => "ru-MD", "name" => "Russian, Moldova"),
            array("code" => "ru-UA", "name" => "Russian, Ukraine"),
            array("code" => "ry-UA", "name" => "Rusyn"),
            array("code" => "sah", "name" => "Sakha"),
            array("code" => "sg", "name" => "Sango"),
            array("code" => "sa", "name" => "Sanskrit"),
            array("code" => "sat", "name" => "Santali"),
            array("code" => "sc", "name" => "Sardinian"),
            array("code" => "sco", "name" => "Scots"),
            array("code" => "gd", "name" => "Scottish Gaelic"),
            array("code" => "sr", "name" => "Serbian (Cyrillic)"),
            array("code" => "sr-CS", "name" => "Serbian (Latin)"),
            array("code" => "sh", "name" => "Serbo-Croatian"),
            array("code" => "crs", "name" => "Seychellois Creole"),
            array("code" => "sn", "name" => "Shona"),
            array("code" => "ii", "name" => "Sichuan Yi"),
            array("code" => "sd", "name" => "Sindhi"),
            array("code" => "si-LK", "name" => "Sinhala"),
            array("code" => "sk", "name" => "Slovak"),
            array("code" => "sl", "name" => "Slovenian"),
            array("code" => "so", "name" => "Somali"),
            array("code" => "son", "name" => "Songhay"),
            array("code" => "ckb", "name" => "Sorani (Kurdish)"),
            array("code" => "nr", "name" => "Southern Ndebele"),
            array("code" => "sma", "name" => "Southern Sami"),
            array("code" => "st", "name" => "Southern Sotho"),
            array("code" => "es-ES", "name" => "Spanish"),
            array("code" => "es-EM", "name" => "Spanish (Modern)"),
            array("code" => "es-AR", "name" => "Spanish, Argentina"),
            array("code" => "es-BO", "name" => "Spanish, Bolivia"),
            array("code" => "es-CL", "name" => "Spanish, Chile"),
            array("code" => "es-CO", "name" => "Spanish, Colombia"),
            array("code" => "es-CR", "name" => "Spanish, Costa Rica"),
            array("code" => "es-DO", "name" => "Spanish, Dominican Republic"),
            array("code" => "es-EC", "name" => "Spanish, Ecuador"),
            array("code" => "es-SV", "name" => "Spanish, El Salvador"),
            array("code" => "es-GT", "name" => "Spanish, Guatemala"),
            array("code" => "es-HN", "name" => "Spanish, Honduras"),
            array("code" => "es-MX", "name" => "Spanish, Mexico"),
            array("code" => "es-NI", "name" => "Spanish, Nicaragua"),
            array("code" => "es-PA", "name" => "Spanish, Panama"),
            array("code" => "es-PY", "name" => "Spanish, Paraguay"),
            array("code" => "es-PE", "name" => "Spanish, Peru"),
            array("code" => "es-PR", "name" => "Spanish, Puerto Rico"),
            array("code" => "es-US", "name" => "Spanish, United States"),
            array("code" => "es-UY", "name" => "Spanish, Uruguay"),
            array("code" => "es-VE", "name" => "Spanish, Venezuela"),
            array("code" => "su", "name" => "Sundanese"),
            array("code" => "sw", "name" => "Swahili"),
            array("code" => "sw-KE", "name" => "Swahili, Kenya"),
            array("code" => "sw-TZ", "name" => "Swahili, Tanzania"),
            array("code" => "ss", "name" => "Swati"),
            array("code" => "sv-SE", "name" => "Swedish"),
            array("code" => "sv-FI", "name" => "Swedish, Finland"),
            array("code" => "syc", "name" => "Syriac"),
            array("code" => "tl", "name" => "Tagalog"),
            array("code" => "ty", "name" => "Tahitian"),
            array("code" => "tg", "name" => "Tajik"),
            array("code" => "tzl", "name" => "Talossan"),
            array("code" => "ta", "name" => "Tamil"),
            array("code" => "tt-RU", "name" => "Tatar"),
            array("code" => "te", "name" => "Telugu"),
            array("code" => "kdh", "name" => "Tem (Kotokoli)"),
            array("code" => "th", "name" => "Thai"),
            array("code" => "bo-BT", "name" => "Tibetan"),
            array("code" => "ti", "name" => "Tigrinya"),
            array("code" => "ts", "name" => "Tsonga"),
            array("code" => "tn", "name" => "Tswana"),
            array("code" => "tr", "name" => "Turkish"),
            array("code" => "tr-CY", "name" => "Turkish, Cyprus"),
            array("code" => "tk", "name" => "Turkmen"),
            array("code" => "uk", "name" => "Ukrainian"),
            array("code" => "hsb-DE", "name" => "Upper Sorbian"),
            array("code" => "ur-IN", "name" => "Urdu (India)"),
            array("code" => "ur-PK", "name" => "Urdu (Pakistan)"),
            array("code" => "ug", "name" => "Uyghur"),
            array("code" => "uz", "name" => "Uzbek"),
            array("code" => "val-ES", "name" => "Valencian"),
            array("code" => "ve", "name" => "Venda"),
            array("code" => "vec", "name" => "Venetian"),
            array("code" => "vi", "name" => "Vietnamese"),
            array("code" => "wa", "name" => "Walloon"),
            array("code" => "cy", "name" => "Welsh"),
            array("code" => "wo", "name" => "Wolof"),
            array("code" => "xh", "name" => "Xhosa"),
            array("code" => "yi", "name" => "Yiddish"),
            array("code" => "yo", "name" => "Yoruba"),
            array("code" => "zea", "name" => "Zeelandic"),
            array("code" => "zu", "name" => "Zulu")
        );
        Language::insert($data);
    }
}
